### PR TITLE
Create zh_TW language file

### PR DESCRIPTION
**Pull request by vongola12324**
* Create zh_TW language file which based on zh_CN language file.
* Add zh_TW fonts (otf file)

### CODE REVIEW

**Comment by jyhsu2000** [comment]
Good.
Expect for update.

**Comment by LaChal** [comment]
Hi vongola12324 and jyhsu2000!

Welcome here, and thank you for the translation!

Concerning the OTF format, we're waiting confirmation it will work on all platform before merging.

**Comment by vongola12324** [comment]
Hi LaChal,  

I have found a font similar to NotoSans, the original font I commit, named SourceHanSans.
There are rtf file of it.
 
Regards,
Vongola

**Comment by LaChal** [comment]
All right!

The font will be changed if there're problems with the actual one.

**Comment by LaChal** [comment]
I have corrected this translation.
But git changed the Windows neuw lines (CRLF) to Unix ones (LF). I could not avoid this...

**Comment by vongola12324** [comment]
Oops, I used MAC OS X to translate the zh_TW file, but MAC use CR as a change line character.
Will those CR character affect the operating of MCEdit?

And, did I make something wrong in the translation file?

**Comment by LaChal** [comment]
The new line type does no matter for MCEdit. The program handles them internally. I warned you in case of you text editor can't handle other newlines than CRLF.

You can base your translation on any other .trn file!
What was wrong in your resource were the missing spaces after the empty t## lines. These spaces are mandatory. To avoid future problems, make your file editor not strip spaces at the end of the lines.

**Comment by vongola12324** [comment]
Ok, I'll pay attention on it.

About the missing space, it's my bad.
My Editor will remove space at the end of sentence.
I'm sorry.
Do I need to fix that and create another Pull Request ?

**Comment by LaChal** [comment]
No probelm!
I know that some editors have the blank space stripping enabled by default. Just change this settings when you work on MCEdit translations, and all be fine ;)

Please, consider to sync your branch from this one before modifying this translation. The blank space stuff has been corrected ;)

**Comment by Khroki** [comment]
Are we using the SourceHansSans font? It is currently doubling the size of some builds due to the fonts taking up 30mb. If we're not I'd like to delete them.

**Comment by OniOniOn-** [comment]
I could remove unnessesary letters in the font file if needed...

**Comment by Khroki** [comment]
If we can get it under 8mb each that would be a ton closer to the other fonts we have.

**Comment by OniOniOn-** [comment]
You can use FontCreator to remove letters that are not chinese. I don't know if only simplified Chinese is used or others so we need translator to help with this.

**Comment by Khroki** [comment]
Either that or we need a lower-res font, even cutting out 3/4 of the font it's still way bigger than the full English/Korean ones.

**Pull request merged**
