### PR TITLE
A few more Swedish translations

### PR DESCRIPTION
**Pull request by TropicSapling**

### CODE REVIEW

**Comment by LaChal** [comment]
@TropicSapling 
Thank you for the update!
If you need some explanation about the context of some strings, just ask :smile:

**Comment by TropicSapling** [comment]
@LaChal I understand the strings, but some are a bit harder to translate due to the Swedish language being structured in a different way. Some words don't really exist in Swedish and some sentences I need more information about to translate.

Then there's also a lot of words I just haven't started translating yet :)

**Comment by LaChal** [comment]
I understand that pretty well :smile:
All the same for French language. E.G: English "chunk" can be translated with the French "morceau", "gros morceau", "part", "partie", "bille", etc. In English, "morceau" can be "cut", "piece","morcel", etc.
The official French Minecraft Wiki uses the word "tronçon". (I shall revise the French MCEdit translation...)
Badly, no Swedish official Wiki :confused:

Personally, I also use online translation and dictionaries to find what word can fit.

By the way, a string is missing: https://github.com/Khroki/MCEdit-Unified/blob/3186e7b73bcb4e5147df29ba30b85859a464b5e8/lang/sv_SE.trn#L738
Since you did not yet translatd it, just don't bother with, I'll resore it!

**Comment by TropicSapling** [comment]
Ok :)

**Pull request merged**
