### PR TITLE
Made site a little friendlier, if possible

### PR DESCRIPTION
**Pull request by DragonQuiz**
sorry about all the commits (don't know how to delete them, couldn't find help).
Will try to fix the home page on mobile since the top text will overlay the bottom, making it hard to read, may add a mobile specific page/ warning in the future, if needed.

### CODE REVIEW

**Comment by OniOniOn-** [comment]
What is the link?

**Comment by DragonQuiz** [comment]
You can test out the mobile look using this http://217.199.187.196/testworkingsite.com/ and can compare how it looks to the current site. Also for space saving and other issues I did not add the documentation so don't worry if you get an error.

**Comment by OniOniOn-** [comment]
I don't know why I thought mcedit-unified.net layout was by github for this long...

**Comment by MobileCrafter** [comment]
There is only one "bug"
Device: iPhone 5S

**Comment by DragonQuiz** [comment]
Yeah, that's a problem that I think Ezekiel could fix since he made that




On Thu, Apr 23, 2015 at 8:30 AM -0700, "MobileCrafter" <notifications@github.com> wrote:














There is only one "bug"

Device: iPhone 5S

**Comment by motapc97** [comment]
@DragonQuiz, I noticed that you use "merge" to sync with `Khroki:gh-pages`. In my opinion, you should use "rebase" because when I look to the diff, I see things that already exist in `Khroki:gh-pages`, and that makes it harder to see what changes you actually did.

**Comment by ezfe** [comment]
@MobileCrafter ok I'll look into that, thanks for the alert.

**Comment by ezfe** [comment]
whah who broke mobile

**Comment by ezfe** [comment]
@MobileCrafter is this still an issue? (773912f0f85f937a24363929aca9de66a3160400)

**Comment by ezfe** [comment]
I made some major changes, please re-fork if you plan to add more changes

**Pull request merged**
