### PR TITLE
Update de_DE.trn

### PR DESCRIPTION
**Pull request by L3ice**
fixes and changes

### CODE REVIEW

**Comment by robske110** [comment]
Dass mit der Objekt-ID ist doof
Es sollte Entity-ID bleiben
//
The entity-Id should be called Entity-ID

**Comment by L3ice** [comment]
No because it's already called `Objekt` in other strings.
We don't want a Denglish Language. :wink:

**Comment by robske110** [comment]
Realy, thats not good
Because an entity != Object
And if you realy wanna use Entität in german, bless you.
Also, ich würde entity lassen, sonst wird es wirklich komischn und verwirrend.

**Comment by LaChal** [comment]
As a clue, I left `TileEntity` in the French translation, because it will have been translated to `Entité de tuile`, which means nothing at all, and it is used as a single word, not two.
But `Entity` is translated to `Entité`.

In the Korean, Dutch and both Chinese translations, the term is the English one. The Swedish one is `RutEntity`.

**Comment by robske110** [comment]
So what should we use in german now
DEFINITELY NOT Objekt
I would use Entity
If you want no denglish use Entität

**Comment by Khroki** [comment]
Well, when modders are talking about entities in german, what do they use?

**Comment by robske110** [comment]
Entity 
I'm in an german developement team for PE-Servers and when we're talking about entities we say entity. Why should we name it object? It just doen't make sense. Especially when you are naming classes Object... And you can use Entität, but we don't even use this too.
German:
https://de.m.wikipedia.org/wiki/Entity
English:
https://en.m.wikipedia.org/wiki/Entity

**Comment by Khroki** [comment]
Yeah, prob should just leave it as entity then. If there's a precedent somewhere for the use of objekt we can discuss it more. Especially since objekt is more general than entity. (I have taken some German in the past)

**Comment by robske110** [comment]
Yes objekt==object :)

**Comment by Khroki** [comment]
Just submit a pull request if you want to change it. Also as an aside since you guys know PE, if anyone knows python our pocket support is really shaky.

**Comment by robske110** [comment]
I don't know phyton, but i can look what i can do :)[The PE projects are php, don't know if phyton has realy big differences]
I will submit the PR ;)

**Comment by Khroki** [comment]
Fair enough, thought I'd ask.

**Comment by TropicSapling** [comment]
I know *some* Python but know like nothing about PE so :package:
(I'm probably not able to help since I rarely program in Python)

**Comment by Khroki** [comment]
Eh it's fine, if you want to help out it's appreciated but you don't have to.

**Comment by L3ice** [comment]
I'll just leave this here: http://minecraft-de.gamepedia.com/Objekt

**Comment by Khroki** [comment]
I stand corrected. Even the discussion page uses it.

**Pull request merged**
