### PR TITLE
Button and Door renderers

### PR DESCRIPTION
**Pull request by skinny121**
The pull request adds a renderer for buttons:
2015-07-18 01-22-47-pm
and for doors:
2015-07-18 01-23-47-pm

In implementing these I created functions that take the information that is in the json models, but copied into python and create templates, which can be rendered. This made implementing button/door renderers easier. I have also refactored the fence renderer to use this as well. Although this can currently only be used for models that don't cull faces based on if they are exposed or not. 

I have also:
  * merged the normal fence and nether fence renderers into one as they were doing the same thing.
  * added some documentation about block renderers to hopefully make it easier in future for people to create/change block renderers.

### CODE REVIEW

**Comment by LaChal** [comment]
Nice !

**Comment by TrazLander** [comment]
Man good job with these. People will really appreciate seeing changes like this.

If your still up for doing any more, I'm looking over a debug world here, and most stuff is honestly bearable. But there are a few that are similar to what you just worked on that could really use some help:
* Trap doors (wood, iron)
* Signs (standing, wall)
* Cobblestone wall (+ Mossy)

Signs pull elements from the wood texture in minecraft, but for mcedit I cut up some wood textures and gave standing signs their own crummy texture. Dunno how to handle that.

**Comment by TrazLander** [comment]
And for the hell of it, here's some priority level 2's:
* Piston arm
* Comparators
* Repeaters
* Anvils
* End portal frame, End portal frame w/eye (doesn't show the rotation properly)
* Nether portal (should at least be able to tell which direction it's facing)
* Logs - along x axis? - because we didn't know how to rotate them properly, their sides are incorrect
2015-07-20 06-23-09-pm

And these are probably a bit more of a challenge and will take a ton more time, so they're pretty low priority:
* Banners
* Skulls

**Comment by Khroki** [comment]
Forgot levers, they're using the torch renderer and don't even show half of the states.

**Pull request merged**
