### PR TITLE
Added most 0.13 MCPE beta blocks

### PR DESCRIPTION
**Pull request by jose-vm**
I'm missing adding the correct textures (they currently use the Future Block one). I'll do this later.

### CODE REVIEW

**Comment by OniOniOn-** [comment]
Think we also need to add damage values...
Is there no powered/unpowered states for activator rail?
Also, lever and other stuffs also has tons of directions and on/off...

**Comment by jose-vm** [comment]
Yeah, the priority atm is to have them added.

**Comment by jose-vm** [comment]
Also, we don't know the exact turning values, no one knows if they're the same as PC

**Comment by OniOniOn-** [comment]
You can test with BlockLauncher and data-value supporting WorldEdit scripts. For ex. set block to 17:7 and we can compare it to pc direction.(use X/Y/Z direction for it, debug screen script has one), or just use the sun to be simple. I don't have Android right now so I can't test.. If someone's willing to test, I could teach every detail.

**Comment by LaChal** [comment]
Nice :smile:

We'll wait you finish your tests before mergin. Meanwhile, please pull this repository changes to yours, or we'll have trouble to merge...

**Comment by jose-vm** [comment]
Well, you guys know that there isn't any modding in MCPE for now, right? There's no way I can know data values until Zhuowei fully updates BlockLauncher. The later you guys merge this, the more it'll take for me to figure data values, since we can't edit terrain with other tool that isn't MCEdit.

**Comment by LaChal** [comment]
Did you try to add your changes in the file you can find in the `pymclevel` subfolder in your MCEdit install directory?

**Comment by OniOniOn-** [comment]
Oh sorry forgot about that. But we still have pocketinveditor worldedit right??

**Comment by jose-vm** [comment]
It's a complete fucking mess. It corrupts worlds.

**Comment by OniOniOn-** [comment]
Stonecutter is removed.(just in case)

**Comment by jose-vm** [comment]
The block is still in the code.

**Comment by jose-vm** [comment]
Try adding it with PIE and you'll see it's still there

**Pull request closed without merging**
