### PR TITLE
Update de_DE.trn

### PR DESCRIPTION
**Pull request by violine1101**

### CODE REVIEW

**Comment by LaChal** [comment]
@violine1101: another update for the German translation has been made: #718 
You may want to discuss with the author and make a single PR.

**Comment by robske110** [comment]
No translation for hovering here ...

**Comment by Neui** [comment]
1. There is a line feed at the end
2. I put one of your change into [my PR](https://github.com/Khroki/MCEdit-Unified/pull/718) (the "Seltsam")

**Comment by violine1101** [comment]
@Neui's PR #718 came first (I didn't see it until now) and includes more changes than mine, so I'll close this.

**Pull request closed without merging**
