### PR TITLE
Fence gates changes 

### PR DESCRIPTION
**Pull request by skinny121**
In this pull request I have fixed fence gates rotations and mirroring. Now they act like any other block with a direction.

I have also added a renderer for fence gates(they show if they are open and in which direction they are open):

2015-07-10 02-49-59-pm

### CODE REVIEW

**Comment by naor2013** [comment]
It's really good! Thanks

**Comment by TrazLander** [comment]
Wow sweet! Does it still use the shitty images I cut up and added to the terrain.png?
(these)
screenshot 2015-07-10 01 43 43

Or does it pull from the wood texture like it actually does for minecraft? Shouldn't matter too much since I pulled those from the wood texture anyway.

**Comment by Khroki** [comment]
Very nice, now we just need to fix the regular fence renderer's texturing and fences will be done. Currently if you have multiple kinds of fences in the same chunk it will pick one and texture all of the fences in that chunk with that single wood type.

**Comment by skinny121** [comment]
@TrazLander It uses those textures for the sides and the plank textures for the top(so that it looks solid on top).

@Khroki I forgot to mention that I also fixed that bug. I based the code after the fence renderer and noticed the comment so I ported the fix I made for the fence gates back to the fence renderer.

**Comment by Khroki** [comment]
Ah cool, thanks, that bug has been taunting me forever.

**Pull request merged**
