### PR TITLE
Updated German localisation

### PR DESCRIPTION
**Pull request by Neui**
I added the newest translation and reworded the old binding-translation. I am not quiet happy with it, it could be improved. But it should do it. Uses the tip in my lastest "issue".

### CODE REVIEW

**Comment by Neui** [comment]
I pushed the updated version. I noticed that you actually undo'd some things at 99bd6e23494728393abd73d4af18adc2f53d7c9a when you see the diff. I used the strings i made before your change so the translated text for "Press Ctrl-Esc to unbind" is missing but i think this piece of text will dissapear.

**Comment by LaChal** [comment]
Effectively, the 'Ctrl-Esc' has been removed.

Sorry, I forgot to warn you about the roll back. But we had an issue with the file format...

Also, note that you don't have to duplicate the strings which are the same in English and German. Just let the line blank after the t## marker (and don't strip the trailing space ;) )

**Comment by MobileCrafter** [comment]
Sigh I also translated it...
Oh well.. I also added a bunch of new strings, I make a PR when this is merged.

**Comment by LaChal** [comment]
OK, thank you.

I intended to merge Neui's version manually myself, but I hardly had time to...

**Comment by Neui** [comment]
I just pushed to reflect the changes that were made in the meanwhile.
- Updated Marco Text e02080b524c29038a1bdb4de3615358799060975
- Updated changes in the controlmenu ("opening" was removed) 1e001b186d110d1feb60db1b4d3f90f22684fd09

BTW, I gave @MobileCrafter permission to use my fork so we can put it into one PullRequest. ( https://twitter.com/craftNeui/status/562574321680666624 ) He answered he would do it either today or tomorrow evening (3./4. Feburary).
If you (MobileCrafter) seeing this, you might want to put your changes on my fork branch. If nothing happends, this can be merged and you can create your own.

**Comment by LaChal** [comment]
This pull request has been merged manually.

**Pull request closed without merging**
