### PR TITLE
Site update

### PR DESCRIPTION
**Pull request by DragonQuiz**
Read second commit

Also if anyone has an idea to get rid of the old navbar that would be great since it shows up whenever the browser window is too small to show the new one or on mobile.

You can see the new navbar and req table here: http://79.170.44.145/testworksite.com/

### CODE REVIEW

**Comment by fhfuih** [comment]
Your new tutorial page copyright area still uses "ownership" instead of  "owners". Other pages are all okay.

**Comment by Khroki** [comment]
Just need @ezfe to look over it, as he manages the site.

**Comment by ezfe** [comment]
@DragonQuiz @Khroki Looking through this now

**Comment by ezfe** [comment]
@DragonQuiz Ok, I have a few questions before I merge this:

1. Why does the tutorial dropdown have three sections? MCEdit is the same on all platforms, it just uses different save formats, however opening and editing the files is actually identical.
2. What is "External Tools" under Misc.
3. What was your reason for adding an MCEdit 2 link when there wasn't one previously. I have nothing against it, just curious.

**Comment by ezfe** [comment]
So git broke absolutely everything and it's marked this as closed.

I won't be merging it for a few reasons:

- Some CSS is broken on contributors page
- Duplicate nav-bars. Please edit the existing nav bar instead of adding a new one.
- Bad whitespace; Please use *tabs*.

**Pull request merged**
