### PR TITLE
Added more Translation Strings

### PR DESCRIPTION
**Pull request by MobileCrafter**

### CODE REVIEW

**Comment by martinhanzik** [comment]
This is kinda bad, your commit is undoing a lot of stuff that has nothing to do with translations, you should  sync your changes before doing that, we'll have to close this one probably.

**Comment by naor2013** [comment]
It seems like you're not updated with out last changes so please update your branch and we don't need the strings "MCEdit Unified v1.2.5.0 for Minecraft 1.8" and "MCEdit Unified v1.2.5.0 for Minecraft 1.8 (64bit)" since we'll have to update it every version and only word to translate here is "for" anyway so it's unneeded
Closing for now but commit again with those changes, please
Thanks!

**Comment by MobileCrafter** [comment]
Ok I do.
But could you add an option like {target_version} and then it automaticly updates the version number?
And no this is NOT undoing stuff.
I Copy pasted the leveleditor.py today from the master.
Its just because my fork was old.
Github just diplays it false.
When you want to prove you, copy the leveleditor.py in your MCEdit Version.
It does ONLY change three spaces on line 3158, 3166, 3189
:)

**Comment by martinhanzik** [comment]
If you want to sync the changes, pull from the master repository, don't copy any files.

**Comment by naor2013** [comment]
There is something that use target version to change automatically, but you can't translate it..
And I think you probably copy-pasted it from your fork of the master.. Try copy-paste it again and notice you're really in the original master

**Comment by MobileCrafter** [comment]
Ok, I messed something up on the copy paste, like you guys said. I will do Pull again.

**Pull request closed without merging**
