### PR TITLE
Added Swedish language

### PR DESCRIPTION
**Pull request by TropicSapling**
Added Swedish language with so far around 500 translations :)
Some translations might be a bit incorrect since some English words we
don't have in Swedish.

**One questions though**: Is this the only file necessary to add the Swedish language? Or do I need to change some other file(s) too? (I haven't looked at anything more than the lang folder so far)

### CODE REVIEW

**Comment by LaChal** [comment]
Hello @TropicSapling!

Thank you for this new translation :)
I know that finding the right words for an other language can be hard. Sometimes, a web or software translator can help ;)

To answer your question, the only thing to do is to add a `.trn` files corresponding to the rules in the translation documentation.

**Comment by TropicSapling** [comment]
@LaChal Ok, great :D

**Comment by LaChal** [comment]
Oh, right.

These resources are for some strings which aren't translated in Minecraft resources. They are used in the block picker and for inventories.

**Comment by TropicSapling** [comment]
@LaChal Oh well that didn't answer my question though xD

What I'm asking is if I can copy one of the language files there and change it into Swedish? **Will it work?** I haven't looked at the code yet so Idk how the language translation works and therefore I wonder if I can just add a file similar to the ones already existing, or if I have to do more things?

**Comment by LaChal** [comment]
The file format is different: it is the one used by Mojang for their localization code.
However, this is quite simple to work with, and if you add a file called `sv_SE.trn` in this folder, it will be recognized and used by MCEdit.

So, yes, you can copy one of these file and translate the content :smile:

**Comment by TropicSapling** [comment]
@LaChal Ok great, I've worked with Mojang's translation files before so I know how it works :smile:

**Comment by TropicSapling** [comment]
Wait, just one more question:
Why doesn't the files in that folder have any extension? Does that mean my file shouldn't have one either?

**Comment by LaChal** [comment]
Yes, your's must not have any extension.

I gave the `.trn` extension in my post above, but it was an error...

**Comment by TropicSapling** [comment]
@LaChal Ok, good :)

**Comment by LaChal** [comment]
By the way, these files are there because some strings seem to miss in Minecraft. But they are translated in the game.
It may happen that these files won't be used in future versions of MCEdit.
(Some clues has been found, but they were not yet enough explored.)

**Comment by TropicSapling** [comment]
@LaChal Oh well it went quick to translate anyway :)

**Comment by LaChal** [comment]
@TropicSapling: A list of translators is maintained.
Would you like to be added to the translators list?
You will then recieve notifications when major updates occur in the translation resources. ('Major updates' occur whe a dozen of new string to be translated are added or when the translations are refactored (very rare) or when we're close to a release.)
A negative answer will not be considered as an offense, we all have our own private buisness :wink:

**Comment by TropicSapling** [comment]
@LaChal
Sure :D

**Comment by LaChal** [comment]
Done :smile:

**Comment by TropicSapling** [comment]
@LaChal 
Where is the list btw?

**Comment by LaChal** [comment]
No where on the web...

It maintain it on my side, and use it when needed in GitHub.

**Comment by TropicSapling** [comment]
@LaChal Oh :)

**Pull request merged**
