### PR TITLE
small improvement - german translation

### PR DESCRIPTION
**Pull request by MG-5**

### CODE REVIEW

**Comment by robske110** [comment]
Sorry for my mess :(

**Comment by TropicSapling** [comment]
Well this seems better since "erreichen" means "reach" in German according to Google Translate and "nutzen" means "use", but I'm not good at German so idk. Seems better than before anyway :)

**Comment by robske110** [comment]
Erreichen is applicable too, but use is probaly better.
But as this errmsg is displayed because of an wrong display resoloution is reach/erreichen the right word in this context

**Comment by robske110** [comment]
I'm native german

**Comment by TropicSapling** [comment]
Ah well I'm Swedish and learning German :)

**Pull request merged**
