### PR TITLE
wooden_slab id

### PR DESCRIPTION
**Pull request by fhfuih**
Wrong wooden_slab id

### CODE REVIEW

**Comment by OniOniOn-** [comment]
This is correct

**Comment by fhfuih** [comment]
screenshot_2015-07-12-14-14-52

This is what WorldEdit tells me...

**Comment by fhfuih** [comment]
default

I also checked wiki  http://minecraft.gamepedia.com/Pocket_Edition_data_values

**Comment by OniOniOn-** [comment]
'This' was meant to be your commit...

**Comment by fhfuih** [comment]
Oh... :P

**Pull request merged**
