### PR TITLE
Updating site to HTML 5

### PR DESCRIPTION
**Pull request by DragonQuiz**
Removed some unnecessary lines/spaces, added footer to all pages and clarified the requirement page due to crashes on older systems with Pentium 4 processors. Also added away for IE 9 and older browsers to look at the site without to much trouble some. I've began to update the 'about' page with more info on mcedit and started to work on the tutorial side of it (not shown here) also excuse the merge pull (don't know how to make it not show up). Also added  a text.css file so that the footer and the 'hr' can be seen correctly on the site.

### CODE REVIEW

**Comment by martinhanzik** [comment]
Looks good, but why are you not indenting the html? :)

**Comment by DragonQuiz** [comment]
by what do you mean indent the html?

**Comment by motapc97** [comment]
@DragonQuiz Instead of writing:

```html
<html>
<body>
</body>
</html>
```

You should write:

```html
<html>
    <body>
    </body>
</html>
```

That is indent the html :)

**Comment by DragonQuiz** [comment]
Is indenting important? I've never done html coding before/in along time, I have used code free setups (i.e. squarespace, wordpress, etc.) If it needs to be, I'll make another request with the indentation.

**Comment by OniOniOn-** [comment]
I love Sublime Text. It takes care of Indent...

**Comment by martinhanzik** [comment]
It's not immportant for the functionality, regarding html, it works exactly the same, but you can straight away easily see what blocks are built what way if you want to change something. If you're at a starting tag and you need to find the end one, you don't have to go through them and count, you can just look at the indentation, because it needs to be at the same level, if you're doing it consistently.

**Comment by DragonQuiz** [comment]
Is this by what you mean html indexing http://pastebin.com/mwczy2Jj (page is unlisted) or everything inside the html should be indented?

**Comment by martinhanzik** [comment]
I would indent it as http://pastebin.com/yiwVbwhs , being consistent with 4 spaces for every level.
https://phpacademy.org/topics/why-you-should-indent-your-code/30965

**Comment by DragonQuiz** [comment]
I never understood the real reason to indent before, so thanks for the information on that @martinhanzik. So with that mindset should I make another request with the indent or wait until approval?

**Comment by DragonQuiz** [comment]
Revised the site code will redo the pull request soon

**Pull request closed without merging**
